[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "its-compiler-python"
dynamic = ["version"]
description = "Reference Python compiler for Instruction Template Specification (ITS)"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
authors = [{ name = "Alexander Parker", email = "your-email@example.com" }]
keywords = [
    "instruction-template-specification",
    "its",
    "ai-prompts",
    "content-generation",
    "templates",
    "compiler",
    "json-schema",
    "ai-tools",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "jsonschema>=4.17.0",
    "requests>=2.28.0",
    "click>=8.0.0",
    "pydantic>=2.0.0",
    "watchdog>=3.0.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
    "pre-commit>=3.0.0",
    "responses>=0.23.0",
]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
    "responses>=0.23.0",
]
docs = [
    "mkdocs>=1.4.0",
    "mkdocs-material>=9.0.0",
    "mkdocstrings[python]>=0.20.0",
]

[project.urls]
Homepage = "https://github.com/alexanderparker/its-compiler-python"
Documentation = "https://github.com/alexanderparker/its-compiler-python#readme"
Repository = "https://github.com/alexanderparker/its-compiler-python"
Issues = "https://github.com/alexanderparker/its-compiler-python/issues"
Changelog = "https://github.com/alexanderparker/its-compiler-python/blob/main/CHANGELOG.md"
"ITS Specification" = "https://github.com/alexanderparker/instruction-template-specification"

[project.scripts]
its-compile = "its_compiler.cli:main"

[tool.hatch.version]
path = "its_compiler/__init__.py"

[tool.hatch.build.targets.wheel]
include = ["its_compiler"]

[tool.black]
line-length = 88
target-version = ["py38"]
include = "\\.pyi?$"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    ".eggs",
    "*.egg-info",
]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers --strict-config"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

[tool.coverage.run]
source = ["."]
omit = ["tests/*", "test_*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@\\(abc\\.\\)?abstractmethod",
]
